// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHwpN3IlT01Pai4yFzQg6MPs6Sjbqoysw',
    appId: '1:846031477499:web:12706653addc96faa52e5e',
    messagingSenderId: '846031477499',
    projectId: 'neighbor-net-1262b',
    authDomain: 'neighbor-net-1262b.firebaseapp.com',
    storageBucket: 'neighbor-net-1262b.appspot.com',
    measurementId: 'G-28VKMKDNQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnXHWUwZqwZGoqLuEH2G2fUE6tW5JQAU0',
    appId: '1:846031477499:android:559a0e17e305d04da52e5e',
    messagingSenderId: '846031477499',
    projectId: 'neighbor-net-1262b',
    storageBucket: 'neighbor-net-1262b.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHwpN3IlT01Pai4yFzQg6MPs6Sjbqoysw',
    appId: '1:846031477499:web:94bf322885bbf192a52e5e',
    messagingSenderId: '846031477499',
    projectId: 'neighbor-net-1262b',
    authDomain: 'neighbor-net-1262b.firebaseapp.com',
    storageBucket: 'neighbor-net-1262b.appspot.com',
    measurementId: 'G-7K7X1RG384',
  );
}
